### PR TITLE
Query SRA directly for SARS-CoV-2 accessions

### PR DESCRIPTION
**Pull request by mvdbeek**
This uses a more stable API instead of a random yaml that ~~disappeared~~ moved to https://www.ncbi.nlm.nih.gov/projects/genome/sars-cov-2-seqs/ncov-sequences.yaml.
Hopefull this will make it more stable. Also includes a replacement for the genome accessions.

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek do you think it is a good idea to have single files with date __and__ and global file. This would make it easier to incrementally add new data.

**Comment by mvdbeek** [comment]
Not really, we'd need to keep two files in sync, since annotation often changes. Just checkout any version in time if you want to get accessions from a specific timepoint. We should annotate collection and deposition date though.

**Comment by bgruening** [comment]
> We should annotate collection and deposition date though.

Which we would have with file-with-date ... I'm not sure those files needs to be updated, its just a history that is easy accessible. The most up-to-date list is still the one-big-file.

**Comment by mvdbeek** [comment]
> Which we would have with file-with-date ...

That's a different thing. Deposition date is when it has been added to the SRA, that doesn't have to correspond to when we first encountered it in our query.
I don't like duplicating this information that you can easily get from git.
What content do you want to have in those files ? A copy of current_metadata.txt ?

**Comment by bgruening** [comment]
The SRA numbers that have been added by the bot at a particular date. A user might now want to download everything again, but maybe just the new numbers from the last 3 days. This would make it very easy.
We can also do it just locally and offer this on our site.

**Comment by mvdbeek** [comment]
I can add that, but I guess I'd prefer to add a column in current_metadata.txt ? In 2 years we'd have 700 files in that directory otherwise.

**Comment by bgruening** [comment]
That would also work I guess, thanks.

**Pull request merged**
