### PR TITLE
new analysis

### PR DESCRIPTION
**Pull request by subinamehta**

### CODE REVIEW

**Comment by bgruening** [comment]
@subinamehta the workflow image is a little bit large with 2.2MB can you add a smaller one?

**Comment by subinamehta** [comment]
> @subinamehta the workflow image is a little bit large with 2.2MB can you add a smaller one?

Sure

**Comment by subinamehta** [comment]
Done!!

**Comment by bgruening** [comment]
Great! Thanks @subinamehta!

**Pull request merged**
