### PR TITLE
Container with hg38 reference included

### PR DESCRIPTION
**Pull request by bedroesb**
I have 2 questions:

Should I keep this version separate with a tag (like it is now) or add the reference genome to the master container.

Also, should I add the scripts to make this container to this repo or another one? At this moment they can be found here: https://github.com/ELIXIR-Belgium/BioContainers_for_training/tree/master/Covid-19-Galaxy-container

### CODE REVIEW

**Comment by bgruening** [comment]
@bedroesb have you checked if this ref-genome is not already part of the CVMFS?

**Comment by bedroesb** [comment]
@bgruening I don't think CVMFS is configured on the 19.01 galaxy container?

**Comment by bgruening** [comment]
It should. You need to start with --privileged. Why are you using such an old image?

**Comment by bedroesb** [comment]
The other images give me an error on the ephemeris packages during built, that they do not exist. For example if I use galaxy_wait. Weird thing is that if I run the container interactively, they are present.

**Comment by bedroesb** [comment]
@bgruening changed tested and changed documentation to --privileged, thanks for the tip!

**Pull request merged**
