### PR TITLE
Create SARS-CoV2-Variant-Analysis

### PR DESCRIPTION
**Pull request by subinamehta**
Adding a new page for Variant analysis of MS-based data

### CODE REVIEW

**Comment by dannon** [comment]
@subinamehta My understanding is that this site is frozen in time as of January 2022; is this content you might want to add under the covid19 project homepage at https://galaxyproject.org/projects/covid19/ ?

**Comment by subinamehta** [comment]
> @subinamehta My understanding is that this site is frozen in time as of January 2022; is this content you might want to add under the new galaxy covid19 project homepage at https://galaxyproject.org/projects/covid19/ ?

Yeah, I think i can transfer the content over there then, or is there an easy way to do the transfer

**Comment by dannon** [comment]
Unfortunately no automagical way, but it's more or less plain markdown there too, so it shouldn't be too painful :)  Let me know if you have any trouble with it and I can help!

**Comment by subinamehta** [comment]
> Unfortunately no automagical way, but it's more or less plain markdown there too, so it shouldn't be too painful :) Let me know if you have any trouble with it and I can help!

I opened a pull request there in the proteomics section, hopefully, that gets approved.

**Pull request closed without merging**
