### PR TITLE
Update fasterq dump

### PR DESCRIPTION
**Pull request by mvdbeek**
and use @wm75's 2 list workaround for all instances.

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek I also found that updating lofreq will helpt with a few errors that "can't find a loc file" because no variants have been called.

**Comment by mvdbeek** [comment]
To which version ? I updated it last week

**Comment by bgruening** [comment]
2.1.4+galaxy2 ... At least the workflows I used had still old versions. With the new version its better.

**Comment by mvdbeek** [comment]
Hmm, weird, I thought I updated all the tools ... this is not good.

**Pull request merged**
