### PR TITLE
JBrowse integration

### PR DESCRIPTION
**Pull request by dannon**
Working version of jbrowse embedded with a component wrapper; need to fix the styling and more flexibly pass props through to the child iframe (div-based embed was a no-go, and this is functional) -- that is, the vue component will have tracks and other config options as props that get shoved into the iframe, which then instantiates jbrowse.

Sample from the deploy is at: https://deploy-preview-83--gifted-liskov-112081.netlify.com/genomics/jbrowse.html

image

### CODE REVIEW

**Comment by cmdcolin** [comment]
Is there anything that required baseUrl to be added? It is generally not required to manually configure a baseUrl and this is probably the cause of the broken images

**Comment by cmdcolin** [comment]
I can also see there was some careful work taken to programmatically instantiate the browser instance. This is pretty interesting and something we could document better. I think that we optimized for the workflows of just instantiating from config files directly so this is why you probably ran into some friction on this

**Comment by cmdcolin** [comment]
If it is not really something that is needing programmatic instantiation, I'd probably just recommend loading direct from config files though

**Comment by cmdcolin** [comment]
Also not sure if this was intended but I saw it with the div embedding attempts too but the url is /genome/ and the baseUrl is /jbrowse/

**Comment by dannon** [comment]
I set baseUrl because I saw it in the sample config somewhere and assumed I needed it :)  I just tested and you're right, looks like it's safe to drop here since it's resolving stuff relative that directory anyway.  I did build this jbrowse dist using `JBROWSE_PUBLIC_PATH=/jbrowse/`.

The image issue (which I didn't notice until now) is just that I assumed those were bundled into the dist that I copied in here from my local jbrowse build.  I'll have to add those.

I can show you more about what went wrong with the div embedding attempts, but it was failing while trying to execute the initial bundle load; that is, it didn't get far enough for the baseurl to matter.

And, yeah, right now the programmatic work to instantiate the instance isn't really doing much for the example here, but that's the fun work to come -- I think it'll pay off.

**Comment by dannon** [comment]
Closing this -- if we do want to pursue live visualizations we'll want to revisit w/ JBrowse2.

**Pull request closed without merging**
