### PR TITLE
Strip empty lines from comp alignment csv

### PR DESCRIPTION
**Pull request by wm75**
`Cut` will turn empty lines into `.` lines in its output, which the `NCBI accession download` tool will interpret as accession numbers and try to download, then fail. The workflow runs despite this failure because the already downloaded datasets themselves are not in an error state - just the Collection is.

### CODE REVIEW

**Comment by wm75** [comment]
I guess this exposes two kind of strange behaviors of tools/Galaxy, which one might want to address separately:

- should the `Cut` tool have an option to ignore trailing empty lines?
- shouldn't a Collection that's in an error state fail a workflow that uses it?

**Comment by bgruening** [comment]
I guess your comments should be moved to an issue on the Galaxy repo so we do not loose them.

**Comment by wm75** [comment]
@bgruening do you think the option in the `Cut` tool to ignore trailing empty lines is worth having?

**Comment by wm75** [comment]
see https://github.com/galaxyproject/galaxy/issues/9394 for the collections issue

**Pull request merged**
